### ISSUE TITLE
Invoke-graphrequest refreshes the token

### ISSUE THREAD

**Issue by frank9843** [markekraus/PSMSGraph#28]
I noticed the other day that Invoke-graphrequest always calls Update-GraphOauthAccessToken. This surprises me, because if you call Invoke-graphrequest more than once per hour you're inefficient. The type of code I'd want to use (and actually implemented) is something like this:
`While($true){
$GraphAccessToken = Import-GraphOAuthAccessToken -Path $PSScriptRoot'\AccessToken.XML'
        if($GraphAccessToken.IsExpired) {
            $GraphAccessToken | Update-GraphOAuthAccessToken
        }
Invoke-GraphRequest
}` 
However, the if clause is useless and in fact reduces the performance, because it performs an action that is already performed later on anyway. At the very least I'd expect this same if clause before the token is refreshed....
Is there a reason why you refresh the token before every call?

**Comment by markekraus** [comment]
`Update-GraphOauthAccessToken` does not update the token if the token is not expired

https://github.com/markekraus/PSMSGraph/blob/f59d809aa2aaf9ff63d128afa7469f2fc1f82369/PSMSGraph/Public/Update-GraphOauthAccessToken.ps1#L88

This is by design. And keeps from requiring expiration logic in the `Invoke-GraphRequest` function. 

`Update-GraphOauthAccessToken` only updates a valid OAuth token if the `-Force` parameter is supplied.

**Comment by frank9843** [comment]
Ah that's why. Thanks for the info!

**Comment by markekraus** [comment]
Also, the idea is that anyone wanting to use the the OAuth lifecycle management without using `Invoke-GraphRequest` (perhaps direct calls with `System.Net.Http.HttpClient`) can call `Update-GraphOauthAccessToken` before every API request to automatically renew the token if it's required without having to use their own expiration logic. The real purpose of this module is OAuth life cycle management since most of the API functions are now available in the `AzureAD` module.
